---
docker_version: "26.0.0"

# Portainer hostname path prefix
portainer_url_path: portainer
# Portainer edition: ce - Community Edition, ee - Business Edition (license required after deploy)
portainer_edition: ee
# Portainer deployment version
portainer_version: "2.20.0"

# Traefik hostname path prefix
traefik_url_path: traefik
traefik_url_path_headers: "{{ traefik_url_path }}/dashboard"
# Traefik deployment version
traefik_version: "2.11.0"
# Traefik network for reverse proxy
traefik_network_name: proxy
traefik_network_subnet: 10.250.2.0/24

# Gitea deployment version
gitea_version: "1.21.10"
