---
# Bootstrap the Debian based systems
# Path: roles/prereq/tasks/prep-debian.yml

- name: Wait for any possibly running unattended upgrade to finish
  raw: systemd-run --property="After=apt-daily.service apt-daily-upgrade.service" --wait /bin/true
  changed_when: no

- name: Add http_proxy to /etc/apt/apt.conf if http_proxy is defined
  ansible.builtin.lineinfile:
    path: /etc/apt/apt.conf
    line: 'Acquire::http::proxy "{{ http_proxy }}";'
    state: present
  when: http_proxy is defined
  ignore_errors: true

- name: Add https_proxy to /etc/apt/apt.conf if https_proxy is defined
  ansible.builtin.lineinfile:
    path: /etc/apt/apt.conf
    line: 'Acquire::https::proxy "{{ http_proxy }}";'
    state: present
  when: https_proxy is defined
  ignore_errors: true

- name: Install python3 and required packages
  apt:
    name:
    - python3
    - python3-pip
    - python3-docker
    - apache2-utils
    - jq
    - nfs-common
    state: present
    update_cache: true
  environment: {}
