---
# Bootstrap the Red Hat based systems
# Path: roles/prereq/tasks/prep-rhel.yml

- name: Check if SELinux is running
  command: getenforce
  register: sestatus
  changed_when: false

- name: Disable SELinux
  selinux:
    state: disabled
  become: true
  when:
  - '"Enabled" in sestatus.stdout'
  - '"Enforcing" in sestatus.stdout'

- name: Add proxy to /etc/yum.conf if http_proxy is defined
  ini_file:
    path: /etc/yum.conf
    section: main
    option: proxy
    value: "{{ http_proxy }}"
    state: "{{ http_proxy | default(false) | ternary('present', 'absent') }}"
    no_extra_spaces: true
  become: true
  when: http_proxy is defined

- name: Add br_netfilter to /etc/modules-load.d/
  copy:
    content: "br_netfilter"
    dest: /etc/modules-load.d/br_netfilter.conf
    mode: "u=rw,g=,o="

- name: Load br_netfilter
  modprobe:
    name: br_netfilter
    state: present

- name: Set bridge-nf-call-iptables (just to be sure)
  sysctl:
    name: "{{ item }}"
    value: "1"
    state: present
    reload: yes
  loop:
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-ip6tables

- name: Add /usr/local/bin to sudo secure_path
  lineinfile:
    line: "Defaults    secure_path = /sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin"
    regexp: "Defaults(\\s)*secure_path(\\s)*="
    state: present
    insertafter: EOF
    path: /etc/sudoers
    validate: "visudo -cf %s"

- name: Enable epel-release repository
  yum:
    name:
      - epel-release
    state: present

- name: Install python3 and required packages
  yum:
    name:
    - python3
    - python3-pip
    - python3-setuptools
    - httpd-tools
    - jq
    - nfs-utils
    state: present
