---
- name: Create required directory
  file:
    state: directory
    path: /tmp/gitea
    mode: 0755

- name: Setup stack compose files
  template:
    src: gitea.yml.j2
    dest: /tmp/gitea/gitea.yml
    mode: 0644
  # register: gitea_stack

- name: Setup deploy script
  copy:
    src: deploy.sh
    dest: /tmp/gitea/deploy.sh
    mode: 0755

- name: Deploy Gitea stack
  shell: "/tmp/gitea/deploy.sh primary gitea /tmp/gitea/gitea.yml {{ portainer_user }} {{ portainer_password }} https://{{ base_hostname }}/{{ portainer_url_path }}"
  # when: gitea_stack.changed
  when: portainer_hostname is not defined
  register: gitea_deploy

- name: Deploy Gitea stack
  shell: "/tmp/gitea/deploy.sh primary gitea /tmp/gitea/gitea.yml {{ portainer_user }} {{ portainer_password }} https://{{ portainer_hostname }}/{{ portainer_url_path }}"
  # when: gitea_stack.changed
  when: portainer_hostname is defined
  register: gitea_deploy

- name: Debug
  # debug: var=gitea_deploy
  debug: "{{ item }}"
  with_items:
    - "{{ gitea_deploy.stderr|default(omit) }}"
    - "{{ gitea_deploy.stdout|default(omit) }}"
  when: gitea_deploy.changed
