---
- name: Getting basic OS information
  hosts: all
  become: true
  tasks:
    - debug:
        msg:
          - {"host": "{{ ansible_hostname }}", "os_info": {"os_family": "{{ ansible_os_family }}", "distribution": "{{ ansible_distribution }}", "major_version": "{{ ansible_distribution_major_version }}", "os_arch": "{{ ansible_architecture }}", "kernel_version": "{{ ansible_kernel }}"}}
