---
- name: Traefik log rotate
  copy:
    dest: "/etc/logrotate.d/traefik"
    # state: file
    content: |
      {{ docker_local_storage }}/volumes/traefik_logs/_data/*.log {
          daily
          rotate 90
          compress
          missingok
          notifempty
          dateext
          dateformat .%Y%m%d
          create 0644 root root
          postrotate
              docker kill --signal="USR1" $(docker ps | grep traefik | awk '{print $1}')
          endscript
      }
